ci: Suggest sort command (#1504)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -70,8 +70,10 @@ jobs:
           S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
           S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
 
-      - name: Enforce sorted `extensions.toml`
-        run: git diff --exit-code -- extensions.toml
-
-      - name: Enforce sorted `.gitmodules`
-        run: git diff --exit-code -- .gitmodules
+      - name: Enforce sorted `extensions.toml` and `.gitmodules`
+        run: |
+          if ! git diff --exit-code -- extensions.toml .gitmodules; then
+            echo -e "\nERROR: extensions.toml and .gitmodules are not sorted."
+            echo -e "Fix by running:\n  pnpm sort-extensions\n"
+            exit 1
+          fi
